### ISSUE TITLE
Shorten time sleep lengths

### ISSUE THREAD

**Issue by Velocities** [SHUR1K-N/DDART-Disk-Diagnostics-and-Repair-Tool-Python#1]
All I see is sleep being used from the time module, so maybe just import sleep from time so you can just do sleep instead of time.sleep?

**Comment by SHUR1K-N** [comment]
Unequivocally, that is absolutely a much more efficient way to do this!

This was my first ever minor Python—in fact, _coding_—project for my first year in engineering school, for the "Data Structures" class in which I was required to build something around arrays and how elements within it had to be changeable upon interaction. So:

1. I wanted the little delays (hence the sleeps) for... dramatic effect, to demonstrate this program more like some "diagnostic scanning tool" instead of just a snap-and-done sort of deal. This was a _simulation_ after all, it does not _actually_ diagnose or repair anything
2. Yes, importing "sleep" initially and then using it without the "time." bit would be much more efficient, but this _method_ (hah!) just stuck with me since there are other system modules (I believe) that achieve delays as well, and I just had to be sure with my code that whenever I look at it, I just know the delay came from the "time" module and not any other — yeah, I know, definitely silly and inefficient, but it made sense to me that way and that's just how it stuck with me!

Funny how someone even gave this a look, hahah, thanks!
