### ISSUE TITLE
Change import time to from time import sleep

### ISSUE THREAD

**Issue by Velocities** [SHUR1K-N/DDART-Disk-Diagnostics-and-Repair-Tool-Python#2]
This would reduce the amount of text by a decent amount

**Comment by SHUR1K-N** [comment]
Unequivocally, that is absolutely a much more efficient way to do this!

This was my first ever minor Python—in fact, coding—project for my first year in engineering school 3–4 years ago, for the "Data Structures" class in which I was required to build something around arrays and how elements within it had to be changeable upon interaction. So:

I wanted the little delays (hence the sleeps) for... dramatic effect, to demonstrate this program more like some "diagnostic scanning tool" instead of just a snap-and-done sort of deal. This was a simulation after all, it does not actually diagnose or repair anything
Yes, importing "sleep" initially and then using it without the "time." bit would be much more efficient, but this method (hah!) just stuck with me since there are other system modules (I believe) that achieve delays as well, and I just had to be sure with my code that whenever I look at it, I just know the delay came from the "time" module and not any other — yeah, I know, definitely silly and inefficient, but it made sense to me that way and that's just how it stuck with me!
Funny how someone even gave this a look, hahah, thanks!

**Comment by Velocities** [comment]
Oh thank you! Sorry for repeating my issue; I was at school and I had thought the school wifi had a problem sending the data because I didn't see it minutes later (after sending it), lol. Also, Github mobile sucks and doesn't let you send pull requests or edit code, so I tried this instead.

**Comment by SHUR1K-N** [comment]
Ah, understandable, no worries!

GitHub mobile sure does suck; I use OpenHub on mobile, but mostly for basic functionality — try it out!
